apiVersion: v1
kind: Pod
metadata:
  name: nginx-image
  labels:
    app: nginx-app
spec:
  containers:
  - name: nginx-demo-image
    image: nginx
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo Hello World, this is Jayant > /usr/share/nginx/html/index.html"]
          # command: ["/bin/sh", "-c", "echo Hello World, this is Jayant > /usr/share/message"]
      preStop:
        exec:
          command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done"]