apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  selector:
    app: nginx-app  
  ports:
    - protocol: TCP
      port: 8080            
      targetPort: 80      
  type: NodePort          
