apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
spec:
  volumeName: demo-pv 
  accessModes:
    -ReadWriteOnce  
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi 