apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user-container
        image: jayant046/user-repo:latest
        env:
          - name: AUTH_ADDRESS
            # value: "10.100.140.91" 
            value: auth-service.default
