apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: #(Here no matchlabel option, as only this is present so it's there by default)
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80  #(Displayed in the outside wirld on this port)
      targetPort: 8080 #(Port in the application)
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer  #(An outsider reachable address which allows to reach this service, and hence ports exposed by this service. Also incomming traffic is adjusted equally)


# Run by the commands: kubectl apply -f service.yaml (to create the services)
# kubectl get services  (To list all services)
# minikube service backend (<service name>)