apiVersion: apps/v1
kind: Deployment
metadata: 
  name: story-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story-container
          image: jayant046/kub-first-app:1
          env:
            - name: STORY_VAR
              value: 'story'
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: pvc-host